# Generated by Django 5.0.2 on 2024-02-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photes',
            fields=[
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('images', models.ImageField(upload_to='media/')),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('idno', models.IntegerField(default=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=36)),
                ('gender', models.CharField(max_length=36)),
                ('age', models.DateTimeField()),
                ('phone', models.CharField(max_length=36)),
                ('username', models.CharField(max_length=36)),
                ('password', models.CharField(max_length=36)),
                ('house', models.CharField(max_length=36)),
                ('Village', models.CharField(max_length=36)),
                ('Mandal', models.CharField(max_length=36)),
                ('Distaic', models.CharField(max_length=36)),
                ('States', models.CharField(max_length=36)),
                ('PinCode', models.CharField(max_length=36)),
            ],
        ),
    ]
