# Generated by Django 5.0.2 on 2024-02-14 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='idno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
