# Generated by Django 5.0.2 on 2024-02-16 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_register_idno'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total',
            fields=[
                ('idno', models.IntegerField(primary_key=True, serialize=False)),
                ('Total', models.CharField(max_length=30)),
            ],
        ),
    ]
